import Link from "next/link";
import { mockInstructorDashboard, mockLearnerProfiles } from "@/lib/instructor-operations/mock-data";
import { MetricCard } from "./metric-card";

const severityStyle = { low: "bg-sky-50 text-sky-700", medium: "bg-amber-50 text-amber-800", high: "bg-rose-50 text-rose-800" };

export function InstructorConsole() {
  const dashboard = mockInstructorDashboard;
  return <><header className="mb-8"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-indigo-700">Operations</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Instructor Console</h1><p className="mt-2 max-w-2xl text-slate-600">Monitor cohort momentum, learner readiness, review demand, and intervention priorities.</p></header><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard detail="Across active cohorts" label="Learners in progress" value={dashboard.learners_in_progress} /><MetricCard detail="Eligible for credential review" label="Certification ready" value={dashboard.certification_ready_count} /><MetricCard detail="Lab submissions awaiting action" label="Pending lab reviews" value={dashboard.pending_lab_reviews} /><MetricCard detail="Open or monitored flags" label="Learner risk flags" value={dashboard.risk_flags.length} /></div>

  <section className="mt-8"><div className="mb-4 flex items-end justify-between"><div><p className="text-xs font-semibold uppercase tracking-wider text-indigo-700">Programs</p><h2 className="mt-1 text-2xl font-semibold">Training cohorts</h2></div><Link className="text-sm font-semibold text-indigo-700" href="/people">View learners</Link></div><div className="grid gap-4 lg:grid-cols-2">{dashboard.cohorts.map((cohort) => <article className="rounded-xl border border-slate-200 bg-white p-5" key={cohort.id}><div className="flex items-start justify-between gap-4"><div><h3 className="font-semibold">{cohort.name}</h3><p className="mt-1 text-sm text-slate-500">{cohort.program_title}</p></div><span className="rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-medium capitalize text-emerald-700">{cohort.status}</span></div><div className="mt-5 flex justify-between text-xs text-slate-500"><span>{cohort.learner_ids.length} learners</span><span>{cohort.progress_percent}% average</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-slate-200"><div className="h-full rounded-full bg-indigo-600" style={{ width: `${cohort.progress_percent}%` }} /></div><p className="mt-3 text-xs text-slate-400">{cohort.start_date} through {cohort.end_date}</p></article>)}</div></section>

  <div className="mt-8 grid gap-6 xl:grid-cols-2"><section className="rounded-xl border border-slate-200 bg-white p-6"><div className="flex items-end justify-between"><div><p className="text-xs font-semibold uppercase tracking-wider text-indigo-700">Assessment activity</p><h2 className="mt-1 text-xl font-semibold">Recent attempts</h2></div></div><div className="mt-5 divide-y divide-slate-100">{dashboard.recent_assessment_activity.map((activity) => <div className="flex items-center justify-between gap-4 py-3" key={activity.id}><div><Link className="text-sm font-medium hover:text-indigo-700" href={`/people/${activity.learner_id}`}>{activity.learner_name}</Link><p className="mt-1 text-xs text-slate-500">{activity.assessment_title}</p></div><div className="text-right"><p className="text-sm font-semibold capitalize">{activity.status.replaceAll("_", " ")}</p><p className="text-xs text-slate-400">{activity.score !== null ? `${activity.score}%` : "Human review"}</p></div></div>)}</div></section><section className="rounded-xl border border-slate-200 bg-white p-6"><p className="text-xs font-semibold uppercase tracking-wider text-indigo-700">Instructor actions</p><h2 className="mt-1 text-xl font-semibold">Recommended next steps</h2><div className="mt-5 grid gap-3">{dashboard.recommended_actions.map((action) => <Link className="rounded-lg border border-slate-200 p-4 hover:border-indigo-300 hover:bg-indigo-50/30" href={action.href} key={action.id}><div className="flex items-start justify-between gap-3"><span className="text-sm font-semibold">{action.title}</span>{action.priority === "high" ? <span className="rounded bg-rose-50 px-2 py-0.5 text-xs text-rose-700">High</span> : null}</div><span className="mt-1 block text-xs leading-5 text-slate-500">{action.description}</span></Link>)}</div></section></div>

  <section className="mt-8 rounded-xl border border-slate-200 bg-white p-6"><div className="flex items-end justify-between"><div><p className="text-xs font-semibold uppercase tracking-wider text-rose-700">Learner risk</p><h2 className="mt-1 text-xl font-semibold">Flags requiring attention</h2></div><Link className="text-sm font-semibold text-indigo-700" href="/reviews">Open review queue</Link></div><div className="mt-5 grid gap-3 md:grid-cols-3">{dashboard.risk_flags.map((flag) => { const learner = mockLearnerProfiles.find((item) => item.id === flag.learner_id); return <article className="rounded-lg border border-slate-200 p-4" key={flag.id}><div className="flex justify-between gap-3"><span className={`rounded px-2 py-0.5 text-xs font-medium capitalize ${severityStyle[flag.severity]}`}>{flag.severity}</span><span className="text-xs capitalize text-slate-400">{flag.category}</span></div><h3 className="mt-3 text-sm font-semibold">{flag.title}</h3><p className="mt-1 text-xs leading-5 text-slate-500">{flag.description}</p>{learner ? <Link className="mt-3 inline-block text-xs font-semibold text-indigo-700" href={`/people/${learner.id}`}>{learner.display_name} -&gt;</Link> : null}</article>; })}</div></section></>;
}
