import Link from "next/link";
import { mockCohorts } from "@/lib/instructor-operations/mock-data";
import type { LearnerProfile as LearnerProfileData } from "@/lib/instructor-operations/types";

const severityStyle = { low: "border-sky-200 bg-sky-50", medium: "border-amber-200 bg-amber-50", high: "border-rose-200 bg-rose-50" };

export function LearnerProfile({ learner }: { learner: LearnerProfileData }) {
  const cohort = mockCohorts.find((item) => item.id === learner.cohort_id);
  return <><Link className="text-sm font-medium text-indigo-700" href="/people">&lt;- Back to people</Link><header className="mt-5 rounded-2xl bg-slate-950 p-7 text-white sm:p-9"><div className="flex flex-wrap items-start gap-5"><div className="flex h-16 w-16 items-center justify-center rounded-full bg-indigo-400/20 text-xl font-semibold text-indigo-200">{learner.display_name.split(" ").map((part) => part[0]).join("")}</div><div className="flex-1"><p className="text-xs font-semibold uppercase tracking-wider text-indigo-300">{learner.role.replaceAll("_", " ")}</p><h1 className="mt-1 text-3xl font-semibold">{learner.display_name}</h1><p className="mt-2 text-sm text-slate-300">{learner.email} - {learner.classification}</p><p className="mt-1 text-xs text-slate-400">{cohort?.name} - Last active {learner.last_active_at.slice(0, 10)}</p></div></div></header>

  {learner.risk_flags.length ? <section className="mt-6"><p className="mb-3 text-xs font-semibold uppercase tracking-wider text-rose-700">Risk flags</p><div className="grid gap-3 md:grid-cols-2">{learner.risk_flags.map((flag) => <article className={`rounded-xl border p-4 ${severityStyle[flag.severity]}`} key={flag.id}><div className="flex justify-between gap-3"><h2 className="font-semibold">{flag.title}</h2><span className="text-xs font-medium capitalize">{flag.severity}</span></div><p className="mt-2 text-sm leading-6 text-slate-600">{flag.description}</p></article>)}</div></section> : null}

  <div className="mt-6 grid gap-6 xl:grid-cols-2"><section className="rounded-xl border border-slate-200 bg-white p-6"><p className="text-xs font-semibold uppercase tracking-wider text-indigo-700">Certifications</p><h2 className="mt-1 text-xl font-semibold">Assigned credentials</h2><div className="mt-4 grid gap-3">{learner.assigned_certifications.map((assignment) => <div className="rounded-lg bg-slate-50 p-4" key={assignment.certification_id}><div className="flex justify-between gap-3"><Link className="text-sm font-semibold" href={`/certifications/${assignment.certification_id}`}>{assignment.title}</Link><span className="text-xs capitalize text-slate-500">{assignment.progress.eligibility_status.replaceAll("_", " ")}</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-slate-200"><div className="h-full bg-indigo-600" style={{ width: `${assignment.progress.progress_percent}%` }} /></div><p className="mt-1 text-right text-xs text-slate-400">{assignment.progress.progress_percent}%</p></div>)}</div></section><section className="rounded-xl border border-slate-200 bg-white p-6"><p className="text-xs font-semibold uppercase tracking-wider text-indigo-700">Courses</p><h2 className="mt-1 text-xl font-semibold">Training progress</h2><div className="mt-4 grid gap-3">{learner.course_progress.map((course) => <div className="rounded-lg bg-slate-50 p-4" key={course.course_id}><div className="flex justify-between gap-3"><span className="text-sm font-semibold">{course.title}</span><span className="text-sm">{course.progress_percent}%</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-slate-200"><div className="h-full bg-sky-600" style={{ width: `${course.progress_percent}%` }} /></div><div className="mt-3 flex flex-wrap gap-2">{course.modules.map((module) => <span className="rounded bg-white px-2 py-1 text-xs text-slate-500" key={module.module_id}>{module.title}: {module.progress_percent}%</span>)}</div></div>)}</div></section>

  <section className="rounded-xl border border-slate-200 bg-white p-6"><p className="text-xs font-semibold uppercase tracking-wider text-indigo-700">Assessments</p><h2 className="mt-1 text-xl font-semibold">Performance</h2><div className="mt-4 divide-y divide-slate-100">{learner.assessment_performance.map((assessment) => <div className="flex items-center justify-between gap-3 py-3" key={assessment.assessment_id}><div><p className="text-sm font-medium">{assessment.title}</p><p className="text-xs text-slate-400">{assessment.attempt_count} attempt{assessment.attempt_count === 1 ? "" : "s"}</p></div><div className="text-right"><p className="text-sm font-semibold capitalize">{assessment.status.replaceAll("_", " ")}</p><p className="text-xs text-slate-400">{assessment.latest_score !== null ? `${assessment.latest_score}%` : "No score"}</p></div></div>)}</div></section><section className="rounded-xl border border-slate-200 bg-white p-6"><p className="text-xs font-semibold uppercase tracking-wider text-indigo-700">Agent Labs</p><h2 className="mt-1 text-xl font-semibold">Submissions</h2>{learner.lab_submissions.length ? <div className="mt-4 divide-y divide-slate-100">{learner.lab_submissions.map((submission) => <div className="flex items-center justify-between gap-3 py-3" key={submission.submission_id}><div><p className="text-sm font-medium">{submission.scenario_title}</p><p className="text-xs text-slate-400">{submission.submitted_at?.slice(0, 10)}</p></div><div className="text-right"><Link className="text-sm font-semibold capitalize text-indigo-700" href={`/reviews/${submission.submission_id}`}>{submission.status.replaceAll("_", " ")}</Link><p className="text-xs text-slate-400">{submission.score !== null ? `${submission.score}%` : "Awaiting score"}</p></div></div>)}</div> : <p className="mt-4 text-sm text-slate-500">No lab submissions.</p>}</section></div>

  <section className="mt-6 rounded-xl border border-slate-200 bg-white p-6"><p className="text-xs font-semibold uppercase tracking-wider text-emerald-700">Competencies</p><h2 className="mt-1 text-xl font-semibold">Competency progress</h2><div className="mt-5 grid gap-4 md:grid-cols-2">{learner.competency_progress.map((competency) => <div key={competency.competency_id}><div className="flex justify-between text-sm"><span className="font-medium">{competency.competency_name}</span><span className="text-slate-500">{competency.progress_percent}%</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-slate-200"><div className="h-full bg-emerald-600" style={{ width: `${competency.progress_percent}%` }} /></div><p className="mt-1 text-xs text-slate-400">{competency.evidence_count} evidence records</p></div>)}</div></section>

  <section className="mt-6 rounded-xl border border-slate-200 bg-white p-6"><p className="text-xs font-semibold uppercase tracking-wider text-violet-700">Instructor record</p><h2 className="mt-1 text-xl font-semibold">Notes and reviewer feedback</h2>{learner.notes.length ? <div className="mt-4 grid gap-3">{learner.notes.map((note) => <article className="rounded-lg bg-violet-50 p-4" key={note.id}><p className="text-sm leading-6 text-violet-950">{note.body}</p><p className="mt-2 text-xs text-violet-600">{note.author_name} - {note.created_at.slice(0, 10)} - {note.visibility}</p></article>)}</div> : <p className="mt-4 text-sm text-slate-500">No instructor notes.</p>}</section></>;
}
