import { mockOperationsReport } from "@/lib/instructor-operations/mock-data";
import type { ReportingMetric } from "@/lib/instructor-operations/types";

function MetricPanel({ eyebrow, title, metrics, color = "bg-indigo-600" }: { eyebrow: string; title: string; metrics: ReportingMetric[]; color?: string }) {
  return <section className="rounded-xl border border-slate-200 bg-white p-6"><p className="text-xs font-semibold uppercase tracking-wider text-indigo-700">{eyebrow}</p><h2 className="mt-1 text-xl font-semibold">{title}</h2><div className="mt-5 grid gap-4">{metrics.map((metric) => { const percent = metric.total ? Math.round((metric.value / metric.total) * 100) : 0; return <div key={metric.label}><div className="flex justify-between text-sm"><span>{metric.label}</span><span className="text-slate-500">{metric.value}/{metric.total} ({percent}%)</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-slate-200"><div className={`h-full rounded-full ${color}`} style={{ width: `${percent}%` }} /></div></div>; })}</div></section>;
}

export function ReportingDashboard() {
  const report = mockOperationsReport;
  return <><header className="mb-8"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-indigo-700">Operations intelligence</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Reporting Dashboard</h1><p className="mt-2 max-w-2xl text-slate-600">Mock portfolio indicators for training, certification, labs, competencies, risk, and reviewer capacity.</p></header><div className="grid gap-6 lg:grid-cols-2"><MetricPanel eyebrow="Learning" metrics={report.training_completion} title="Training completion overview" /><MetricPanel color="bg-sky-600" eyebrow="Credentials" metrics={report.certification_readiness} title="Certification readiness overview" /><MetricPanel color="bg-amber-500" eyebrow="Practical assessment" metrics={report.lab_outcomes} title="Lab pass/fail overview" /><MetricPanel color="bg-emerald-600" eyebrow="Capability" metrics={report.competency_coverage} title="Competency coverage overview" /></div><div className="mt-6 grid gap-6 lg:grid-cols-[20rem_minmax(0,1fr)]"><section className="rounded-xl border border-slate-200 bg-white p-6"><p className="text-xs font-semibold uppercase tracking-wider text-rose-700">Learner risk</p><h2 className="mt-1 text-xl font-semibold">Risk summary</h2><div className="mt-5 grid gap-3">{report.learner_risk.map((risk) => <div className="flex items-center justify-between rounded-lg bg-slate-50 px-4 py-3" key={risk.severity}><span className="text-sm font-medium capitalize">{risk.severity} severity</span><strong className="text-xl">{risk.count}</strong></div>)}</div></section><section className="rounded-xl border border-slate-200 bg-white p-6"><p className="text-xs font-semibold uppercase tracking-wider text-indigo-700">Reviews</p><h2 className="mt-1 text-xl font-semibold">Reviewer workload summary</h2><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[36rem] text-left text-sm"><thead className="border-b border-slate-200 text-xs uppercase tracking-wide text-slate-400"><tr><th className="pb-3">Reviewer</th><th className="pb-3">Assigned</th><th className="pb-3">Overdue</th><th className="pb-3">Completed</th><th className="pb-3">Capacity</th></tr></thead><tbody className="divide-y divide-slate-100">{report.reviewer_workload.map((reviewer) => <tr key={reviewer.reviewer_id}><td className="py-4 font-medium">{reviewer.reviewer_name}</td><td className="py-4">{reviewer.assigned_count}</td><td className="py-4">{reviewer.overdue_count}</td><td className="py-4">{reviewer.completed_this_week}</td><td className="py-4 capitalize text-slate-500">{reviewer.capacity_status.replaceAll("_", " ")}</td></tr>)}</tbody></table></div></section></div></>;
}
