import Link from "next/link";
import { AuthGate } from "@/components/auth/auth-gate";
import { getCurrentProfile, getCurrentSession } from "@/lib/auth/session";
import { roleLabels, rolePermissions } from "@/lib/auth/roles";

export const dynamic = "force-dynamic";

export default async function AccountPage() {
  const [user, session] = await Promise.all([getCurrentProfile(), getCurrentSession()]);
  if (!user) return <AuthGate user={null}><></></AuthGate>;
  const permissions = Array.from(new Set(user.roles.flatMap((role) => rolePermissions[role])));
  const mode = user.source === "supabase" ? "SUPABASE MODE" : "MOCK MODE";
  const provider = session?.user.app_metadata.provider ?? session?.user.identities?.[0]?.provider ?? (user.source === "mock" ? "mock" : "unknown");
  const sessionStatus = user.source === "mock" ? "Mock fallback active" : session ? "Authenticated session active" : "Session unavailable";

  return <AuthGate user={user}><div className="mx-auto max-w-4xl"><div className={`mb-4 rounded-lg border px-4 py-3 text-center text-sm font-bold tracking-[0.18em] ${user.source === "supabase" ? "border-emerald-300 bg-emerald-50 text-emerald-800" : "border-amber-300 bg-amber-50 text-amber-800"}`}>{mode}</div><header className="rounded-2xl bg-slate-950 p-8 text-white"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-sky-400">Account</p><h1 className="mt-2 text-3xl font-semibold">{user.display_name}</h1><p className="mt-2 text-slate-300">{user.email} - {user.classification}</p><p className="mt-5 break-all text-xs text-slate-400">User ID: {user.id}</p></header><div className="mt-6 grid gap-6 md:grid-cols-2"><section className="rounded-xl border border-slate-200 bg-white p-6"><p className="text-xs font-semibold uppercase tracking-wider text-sky-700">Authentication</p><dl className="mt-4 grid gap-3 text-sm"><div><dt className="text-slate-400">Session status</dt><dd className="mt-1 font-medium">{sessionStatus}</dd></div><div><dt className="text-slate-400">Auth provider</dt><dd className="mt-1 font-medium capitalize">{provider}</dd></div><div><dt className="text-slate-400">Email</dt><dd className="mt-1 break-all font-medium">{user.email}</dd></div></dl></section><section className="rounded-xl border border-slate-200 bg-white p-6"><p className="text-xs font-semibold uppercase tracking-wider text-sky-700">Profile data</p><dl className="mt-4 grid gap-3 text-sm"><div><dt className="text-slate-400">Display name</dt><dd className="mt-1 font-medium">{user.display_name}</dd></div><div><dt className="text-slate-400">Classification</dt><dd className="mt-1 font-medium">{user.classification}</dd></div><div><dt className="text-slate-400">Source</dt><dd className="mt-1 font-medium capitalize">{user.source}</dd></div></dl></section><section className="rounded-xl border border-slate-200 bg-white p-6"><p className="text-xs font-semibold uppercase tracking-wider text-sky-700">Roles</p><div className="mt-4 flex flex-wrap gap-2">{user.roles.length ? user.roles.map((role) => <span className="rounded-full bg-sky-50 px-3 py-1 text-sm font-medium text-sky-800" key={role}>{roleLabels[role]}</span>) : <span className="text-sm text-slate-500">No application roles assigned.</span>}</div></section><section className="rounded-xl border border-slate-200 bg-white p-6"><p className="text-xs font-semibold uppercase tracking-wider text-sky-700">Effective permissions</p><ul className="mt-4 grid gap-2 text-sm text-slate-600">{permissions.map((permission) => <li key={permission}>{permission.replaceAll("_", " ")}</li>)}</ul></section></div><div className="mt-6 flex flex-wrap gap-4"><Link className="rounded-lg border border-slate-300 bg-white px-4 py-2 text-sm font-medium" href="/admin/diagnostics">Admin diagnostics</Link><Link className="rounded-lg bg-slate-900 px-4 py-2 text-sm font-medium text-white" href="/logout">Sign out</Link></div></div></AuthGate>;
}
