import Link from "next/link";
import { mockAdminAuditEvents, mockAdminUsers } from "@/lib/admin/mock-data";

export function AdminDashboard() {
  const active = mockAdminUsers.filter((user) => user.status === "active").length;
  const admins = mockAdminUsers.filter((user) => user.role_assignments.some((item) => item.role === "admin")).length;
  const cohortMembers = mockAdminUsers.filter((user) => user.cohort_assignments.length > 0).length;
  return <><header className="mb-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-indigo-700">Access control</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Administration</h1><p className="mt-2 max-w-2xl text-slate-600">Review mock profiles, roles, cohort assignments, access levels, and recent audit activity.</p></div><Link className="rounded-lg border border-indigo-300 bg-white px-4 py-2 text-sm font-semibold text-indigo-700" href="/admin/diagnostics">Run diagnostics</Link></div></header><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Total users", mockAdminUsers.length], ["Active profiles", active], ["Administrators", admins], ["Cohort members", cohortMembers]].map(([label, value]) => <article className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm" key={label}><p className="text-sm text-slate-500">{label}</p><strong className="mt-2 block text-3xl">{value}</strong></article>)}</div><div className="mt-8 grid gap-6 lg:grid-cols-[minmax(0,1fr)_22rem]"><section className="rounded-xl border border-slate-200 bg-white p-6"><div className="flex items-end justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-wider text-indigo-700">Users</p><h2 className="mt-1 text-xl font-semibold">Role management</h2></div><Link className="text-sm font-semibold text-indigo-700" href="/admin/users">Manage users -&gt;</Link></div><div className="mt-5 divide-y divide-slate-100">{mockAdminUsers.slice(0, 4).map((user) => <div className="flex items-center justify-between gap-4 py-3" key={user.id}><div><p className="text-sm font-medium">{user.display_name}</p><p className="text-xs text-slate-400">{user.classification}</p></div><span className="text-xs capitalize text-slate-500">{user.access_summary.access_level.replaceAll("_", " ")}</span></div>)}</div></section><section className="rounded-xl border border-slate-200 bg-white p-6"><p className="text-xs font-semibold uppercase tracking-wider text-indigo-700">Audit preview</p><h2 className="mt-1 text-xl font-semibold">Recent events</h2><div className="mt-5 divide-y divide-slate-100">{mockAdminAuditEvents.slice(0, 5).map((event) => <div className="py-3" key={event.id}><p className="text-sm font-medium">{event.summary}</p><p className="mt-1 text-xs text-slate-400">{event.actor_name} - {event.created_at.slice(0, 10)}</p></div>)}</div></section></div></>;
}
