"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { mockAdminUsers } from "@/lib/admin/mock-data";
import { RoleBadge } from "./role-badge";

export function AdminUserList() {
  const [query, setQuery] = useState("");
  const [status, setStatus] = useState<"all" | "active" | "inactive" | "suspended">("all");
  const users = useMemo(() => { const search = query.trim().toLocaleLowerCase(); return mockAdminUsers.filter((user) => (status === "all" || user.status === status) && (!search || [user.display_name, user.email, user.classification].some((value) => value.toLocaleLowerCase().includes(search)))); }, [query, status]);
  return <><header className="mb-8"><Link className="text-sm font-medium text-indigo-700" href="/admin">&lt;- Administration</Link><h1 className="mt-4 text-3xl font-semibold tracking-tight">User access</h1><p className="mt-2 text-slate-600">Inspect profiles and stage mock role or cohort changes.</p></header><section className="rounded-xl border border-slate-200 bg-white p-5"><div className="grid gap-3 md:grid-cols-[1fr_12rem]"><input className="rounded-lg border border-slate-300 px-4 py-2.5 text-sm" onChange={(event) => setQuery(event.target.value)} placeholder="Search name, email, or classification" type="search" value={query} /><select className="rounded-lg border border-slate-300 px-3 py-2.5 text-sm" onChange={(event) => setStatus(event.target.value as typeof status)} value={status}><option value="all">All statuses</option><option value="active">Active</option><option value="inactive">Inactive</option><option value="suspended">Suspended</option></select></div></section><div className="mt-5 grid gap-4">{users.map((user) => <article className="rounded-xl border border-slate-200 bg-white p-5" key={user.id}><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="text-lg font-semibold">{user.display_name}</h2><p className="mt-1 text-sm text-slate-500">{user.email} - {user.classification}</p><div className="mt-3 flex flex-wrap gap-2">{user.role_assignments.map((assignment) => <RoleBadge key={assignment.id} role={assignment.role} />)}</div></div><div className="text-right"><span className={`rounded-full px-2.5 py-1 text-xs font-medium capitalize ${user.status === "active" ? "bg-emerald-50 text-emerald-700" : "bg-slate-100 text-slate-600"}`}>{user.status}</span><p className="mt-3 text-xs capitalize text-slate-400">{user.access_summary.access_level.replaceAll("_", " ")}</p></div></div><div className="mt-4 flex items-center justify-between border-t border-slate-100 pt-4"><span className="text-xs text-slate-500">{user.cohort_assignments.length} cohort assignment{user.cohort_assignments.length === 1 ? "" : "s"}</span><Link className="text-sm font-semibold text-indigo-700" href={`/admin/users/${user.id}`}>Manage access -&gt;</Link></div></article>)}</div></>;
}
