import Link from "next/link";
import type { CertificationProgress, CertificationTrack } from "@/lib/certifications/types";

export function CertificationCard({ certification, progress }: { certification: CertificationTrack; progress?: CertificationProgress }) {
  const courseCount = certification.requirements.filter((item) => item.requirement_type === "course").length;
  const assessmentCount = certification.requirements.filter((item) => item.requirement_type === "assessment").length;

  return <article className="flex h-full flex-col rounded-xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-start justify-between gap-4"><span className="rounded-full bg-sky-50 px-3 py-1 text-xs font-semibold text-sky-700">{certification.level.name}</span><span className="text-xs font-medium capitalize text-slate-500">{progress?.eligibility_status.replaceAll("_", " ") ?? "not started"}</span></div><h2 className="mt-4 text-xl font-semibold tracking-tight">{certification.title}</h2><p className="mt-2 flex-1 text-sm leading-6 text-slate-600">{certification.summary}</p><div className="mt-5 grid grid-cols-3 gap-2 text-center text-xs"><div className="rounded-lg bg-slate-50 p-2"><strong className="block text-base">{courseCount}</strong>Courses</div><div className="rounded-lg bg-slate-50 p-2"><strong className="block text-base">{assessmentCount}</strong>Assessments</div><div className="rounded-lg bg-slate-50 p-2"><strong className="block text-base">{certification.passing_score}%</strong>Passing</div></div>{progress ? <div className="mt-5"><div className="mb-1 flex justify-between text-xs text-slate-500"><span>Progress</span><span>{progress.progress_percent}%</span></div><div className="h-2 overflow-hidden rounded-full bg-slate-200"><div className="h-full rounded-full bg-sky-600" style={{ width: `${progress.progress_percent}%` }} /></div></div> : null}<Link className="mt-5 text-sm font-semibold text-sky-700" href={`/certifications/${certification.id}`}>View certification -&gt;</Link></article>;
}
